### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int' using custom wav2vec2

### ISSUE THREAD

**Issue by C00reNUT** [MahmoudAshraf97/ctc-forced-aligner#18] opened 2024-09-21 14:24 UTC
Hello,

Thank you for marking this public! 

Everything works very nicely with the default model, but I wanted to compare the results using wav2vec2 model finetuned on my own, czech language using 

`ctc-forced-aligner --audio_path "Moudry_zlatnik.wav" --text_path "Moudry_zlatnik.txt" --language "ces" --romanize --alignment_model badrex/xlsr-czech`

the model is from repo https://huggingface.co/badrex/xlsr-czech 

When I run the cli command i get:

```
/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/ctc-forced-aligner/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/ctc-forced-aligner/bin/ctc-forced-aligner", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/ctc-forced-aligner/lib/python3.11/site-packages/ctc_forced_aligner/align.py", line 151, in cli
    segments, scores, blank_id = get_alignments(
                                 ^^^^^^^^^^^^^^^
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/ctc-forced-aligner/lib/python3.11/site-packages/ctc_forced_aligner/alignment_utils.py", line 231, in get_alignments
    path, scores = forced_align(
                   ^^^^^^^^^^^^^
  File "/mnt/a0b764eb-cdc5-4f46-9a2e-e2f11deba631/PYTHON_CACHE/ctc-forced-aligner/lib/python3.11/site-packages/ctc_forced_aligner/alignment_utils.py", line 199, in forced_align
    if blank >= log_probs.shape[-1] or blank < 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
``` 
Any ideas how I could fix this?

**Comment by MahmoudAshraf97** [comment] 2024-09-22 13:27
should be fixed in the last commit

**Comment by MahmoudAshraf97** [comment] 2024-09-23 08:54
I just tested it again, I couldn't reproduce the same error, please note that the usage instructions have ben slightly changed so refer to the readme

**Comment by MahmoudAshraf97** [comment] 2024-09-28 17:08
should be fixed now, btw, if the custom model supports the whole vocabulary of the language you should not romanize, only romanize if you are using the default model or using English model for a language other than English

**Closed by MahmoudAshraf97** 2024-09-28 17:08 UTC
